# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.8'

    - name: Check Generated Code Up to Date
      run: |
        make generate
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Uncommitted changes detected:"
          git status --porcelain
          exit 1
        else
          echo "No uncommitted changes detected."
        fi

    - name: Build
      run: make build

    - name: Test
      run: make test
